title: 
#logo
description: I'm a Senior Research Associate on the Department of Soil Mapping and Environmental Informatics, Institute for Soil Sciences, Hungary.
#show_downloads: true
theme: jekyyl-theme-architect

